# Generated by Django 4.2.7 on 2025-05-13 07:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_employerprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
